# Generated by Django 4.0.1 on 2022-02-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=1000)),
                ('Year', models.PositiveIntegerField()),
                ('Rated', models.CharField(blank=True, max_length=255)),
                ('Released', models.CharField(blank=True, max_length=255)),
                ('Runtime', models.CharField(blank=True, max_length=255)),
                ('Genre', models.CharField(blank=True, max_length=500)),
                ('Director', models.CharField(blank=True, max_length=500)),
                ('Writer', models.CharField(blank=True, max_length=500)),
                ('Actors', models.CharField(blank=True, max_length=1000)),
                ('Plot', models.TextField(blank=True)),
                ('Language', models.CharField(blank=True, max_length=255)),
                ('Country', models.CharField(blank=True, max_length=255)),
                ('Awards', models.CharField(blank=True, max_length=1000)),
                ('Poster', models.CharField(blank=True, max_length=1000)),
                ('Ratings', models.JSONField(default=list)),
                ('Metascore', models.CharField(blank=True, max_length=255)),
                ('imdbRating', models.CharField(blank=True, max_length=255)),
                ('imdbVotes', models.CharField(blank=True, max_length=255)),
                ('imdbID', models.CharField(blank=True, max_length=255)),
                ('DVD', models.CharField(blank=True, max_length=255)),
                ('BoxOffice', models.CharField(blank=True, max_length=255)),
                ('Production', models.CharField(blank=True, max_length=255)),
                ('Website', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
